/**
 * The certification fixture's A-memory cells (phase 14 contract §3.3,
 * `memory-01` … `memory-10`). Every cell here is an executable pin: the
 * hand layer asserts what the owning contracts recorded (kinds, exits,
 * holders, ledger projections), and the byte-pinned cells diff their live
 * bytes against `expected/*.json` — committed once by the committed
 * generator, never regenerated by a gated path (§4.1, §4.4).
 *
 * Two recorded findings shape this suite, both carried in the manifest's
 * provenance notes:
 * - `memory-03` and `memory-04` run at the boundary transport only. The
 *   contract's `CLI` half is unreachable on A-memory: a one-shot process
 *   builds a FRESH `MemoryClaimStore` (`selectEngine`), whose seed is
 *   constructor-only, so no process can ever render another run's denial —
 *   empirically, the second identical CLI run publishes with exit 0. The
 *   exit rows the contract pinned for those halves (11 and 14) are earned
 *   at the CLI by `git-04` and `git-05` over the durable register.
 * - `memory-05`'s crash is seated at the memory factory's declared store
 *   parameters (R2), and `memory-06`'s at the declared hook effect — the
 *   fixture's only two declared-injection postures (§8).
 */

import { describe, expect, it } from "vitest";

import { assembleMemoryStores, type LedgerRecord } from "../../src/index.js";
import {
  CapturingLedger,
  FOREIGN_PLAN,
  ShiftingLedger,
  beta,
  freshAssembly,
  fullDeclaration,
  runRequest,
} from "../app/harness.js";
import { freshStores, GOLDEN, liveWorld } from "../vertical/matrix.js";
import {
  attestDeclaration,
  CrashingLedger,
  crashedHandle,
  docBytes,
  loserEngine,
  memoryDenialScenario,
  memoryDoc,
  memoryPlanScenario,
  memoryRunScenario,
  readExpected,
  runBin,
  type ExpectedScenario,
} from "./drive.js";

// ---------------------------------------------------------------------------
// Suite-local reading helpers — the ledger projection's lenses
// ---------------------------------------------------------------------------

/** One step's recorded transitions, append order — the durable evidence a
 * resume re-judged from (the ledger-projection class's reading). */
const recordedTos = (tail: readonly LedgerRecord[], stepKey: string): readonly string[] =>
  tail.flatMap((record) =>
    record.kind === "step" && record.record.stepKey === stepKey ? [record.record.to] : [],
  );

const stepKeys = (tail: readonly LedgerRecord[]): readonly string[] =>
  tail.flatMap((record) => (record.kind === "step" ? [record.record.stepKey] : []));

/** The committed bytes for one scenario, compared at test time. A missing
 * file or label is a fixture defect (the manifest's orphan laws find it);
 * it is never an excuse to snapshot fresh bytes. */
const expectedScenario = (cell: string, label: string): ExpectedScenario => {
  const doc = readExpected(cell);
  if (doc === null) {
    throw new Error(
      `no committed expected bytes for ${cell} — the reviewed file must exist ` +
        `(generate once with test/certification/generate.ts; never snapshot at test time)`,
    );
  }
  const scenario = doc.scenarios.find((candidate) => candidate.label === label);
  if (scenario === undefined) {
    throw new Error(`${cell} records no scenario labelled "${label}"`);
  }
  return scenario;
};

// ---------------------------------------------------------------------------
// The cells
// ---------------------------------------------------------------------------

describe("the certification fixture · A-memory", () => {
  it("memory-01 · W4 · the double plan renders byte-identical JSON at the same exit — the one envelope needing no projection", () => {
    const first = memoryPlanScenario();
    const doc = docBytes(memoryDoc("main", [beta]));
    const second = runBin(["plan", "--assembly", "memory", "--world", "-", "--json"], {
      input: doc,
    });
    expect(first.status).toBe(0);
    expect(second.status).toBe(first.status);
    expect(second.stdout).toBe(first.stdout);
    expect(second.stderr).toBe("");

    // The byte layer: the recorded envelope, diffed verbatim.
    const recorded = expectedScenario("memory-01", "plan (first of the double)");
    expect(first.status).toBe(recorded.exit);
    expect(first.stdout).toBe(recorded.stdout);
  });

  it("memory-02 · W1 · published without a mint, rendered verbatim on both transports and equal through the pass-through", () => {
    const { child, direct } = memoryRunScenario();
    expect(child.status).toBe(0);
    expect(child.stderr).toBe("");
    const rendered = JSON.parse(child.stdout) as { kind: string; tag: string };
    expect(rendered.kind).toBe("published");
    expect(rendered.tag).toBe(GOLDEN.ladder[0]);

    // The same walk through the boundary door: same kind, same tag — and
    // the process rendered exactly the door value's serialization.
    expect(direct.kind).toBe("published");
    if (direct.kind !== "published") {
      throw new Error("expected a published outcome");
    }
    expect(direct.tag).toBe(GOLDEN.ladder[0]);
    expect(JSON.parse(child.stdout)).toStrictEqual(JSON.parse(JSON.stringify(direct)) as object);

    // The byte layer: the process envelope as reviewed bytes.
    const recorded = expectedScenario("memory-02", "run (the process envelope)");
    expect(child.status).toBe(recorded.exit);
    expect(child.stdout).toBe(recorded.stdout);
    const boundary = expectedScenario("memory-02", "run (the boundary door value)");
    expect(JSON.stringify(direct)).toBe(boundary.stdout);
  });

  it("memory-03 · W5 × I1 · the loser's denial names the winner — the pass-through's stop, at the boundary (CLI half unreachable on A-memory)", () => {
    // The winner promotes and blocks mid-walk, holding the stable-version
    // claim; the loser (the plan's second ordinal over the same store) is
    // denied, and the denial names the winner's attempt id verbatim.
    const { winner, loser } = memoryDenialScenario();
    expect(winner.kind).toBe("blocked");
    if (winner.kind !== "blocked" || winner.handle === null) {
      throw new Error("expected a blocked winner holding the claim");
    }
    expect(loser.kind).toBe("denied");
    if (loser.kind !== "denied") {
      throw new Error("expected a denied outcome");
    }
    expect(loser.holder).toBe(winner.handle.attemptId);
    expect(loser.drives).toStrictEqual([]);

    // The byte layer: the recorded denial, diffed verbatim.
    const recorded = expectedScenario("memory-03", "promote loser (the denied door value)");
    expect(JSON.stringify(loser)).toBe(recorded.stdout);
  });

  it("memory-04 · W5 × I2 · E-08's declared bound, both sides — the explicit conflict at 0 and the published retry at the raised bound (CLI half unreachable on A-memory)", () => {
    // The winner holds the stream's prerelease-sequence lease from a
    // blocked walk; the loser's retry bound is the declared knob: 0 of 0
    // conflicts explicitly, the raised bound's retry lands and publishes.
    const world = liveWorld();
    const winner = freshAssembly();
    const stopped = winner.engine.run(runRequest(world, "main", [beta], attestDeclaration()));
    expect(stopped.kind).toBe("blocked");
    if (stopped.kind !== "blocked" || stopped.planId === null) {
      throw new Error("expected a blocked winner holding the claim");
    }
    const claims = winner.stores.claims;

    const boundZero = loserEngine(stopped.planId, claims, 0).run(runRequest(world, "main", [beta]));
    expect(boundZero.kind).toBe("conflict");
    if (boundZero.kind !== "conflict") {
      throw new Error("expected a conflict outcome");
    }
    expect(boundZero.detail).toContain("0 of 0");
    expect(boundZero.drives).toStrictEqual([]);

    const raised = loserEngine(stopped.planId, claims, 2).run(runRequest(world, "main", [beta]));
    expect(raised.kind).toBe("published");
    if (raised.kind !== "published") {
      throw new Error("expected a published outcome");
    }
    expect(raised.tag).toBe(GOLDEN.ladder[0]);
  });

  it("memory-05 · W1 × I3 · the write-ahead crash window: the start is durable, the fault escapes, the resume equals the uninterrupted run", () => {
    const assembly = freshAssembly();
    const crashing = new CrashingLedger(assembly.stores.ledger);
    const engine = assembleMemoryStores(
      {
        register: assembly.stores.register,
        ledger: crashing,
        claims: assembly.stores.claims,
        channels: assembly.stores.channels,
      },
      { maxRetries: 2 },
    );
    const world = liveWorld();

    // The fault is not a classification: it escapes the door untouched —
    // but only after the publish stage's write-ahead start is durable.
    crashing.armOn("publish");
    expect(() => engine.run(runRequest(world, "main", [beta], fullDeclaration()))).toThrow(
      "the process died between the write-ahead start and the stage's effect",
    );
    const attemptId = crashing.attemptIds[0];
    const planId = crashing.planIds[0];
    if (attemptId === undefined || planId === undefined) {
      throw new Error("fixture broken: the ledger captured no attempt write");
    }
    expect(assembly.stores.ledger.step(attemptId, "publish")).toBe("started");
    const tailBefore = assembly.stores.ledger.tail(attemptId);
    expect(recordedTos(tailBefore, "publish")).toStrictEqual(["started"]);

    // The resume classifies from the recorded tail — never a re-plan —
    // and lands the same published terminal an uninterrupted walk does.
    const outcome = engine.resume(
      crashedHandle(planId, attemptId),
      runRequest(world, "main", [beta], fullDeclaration()),
    );
    expect(outcome.kind).toBe("published");
    if (outcome.kind !== "published") {
      throw new Error("expected a published outcome");
    }
    expect(outcome.tag).toBe(GOLDEN.ladder[0]);

    // Ledger projection: the publish stage re-entered at its durable start
    // and completed once — no third transition; every earlier stage's
    // completed record stood.
    const tail = assembly.stores.ledger.tail(attemptId);
    expect(recordedTos(tail, "publish")).toStrictEqual(["started", "completed"]);
    expect(stepKeys(tail)).toContain("channel-transition");

    // Resumed-equals-uninterrupted: a walk that never crashed lands the
    // identical kind and tag.
    const uninterrupted = freshAssembly().engine.run(
      runRequest(liveWorld(), "main", [beta], fullDeclaration()),
    );
    expect(uninterrupted.kind).toBe("published");
    if (uninterrupted.kind !== "published") {
      throw new Error("expected a published outcome");
    }
    expect(uninterrupted.tag).toBe(outcome.tag);
  });

  it("memory-06 · W1 × I3ext · the declared hook's mid-effect fault: the start is durable, the resume runs the effect exactly once more", () => {
    const stores = freshStores();
    const capturing = new CapturingLedger(stores.ledger);
    const engine = assembleMemoryStores(
      {
        register: stores.register,
        ledger: capturing,
        claims: stores.claims,
        channels: stores.channels,
      },
      { maxRetries: 2 },
    );
    const world = liveWorld();
    const declaration = fullDeclaration();
    const effects = new Map(declaration.hookEffects ?? []);
    let invocations = 0;
    effects.set("announce", (input) => {
      invocations += 1;
      if (invocations === 1) {
        throw new Error("the announce webhook crashed mid-flight");
      }
      return {
        attribution: { attemptId: input.attemptId, actor: "automation" },
        evidence: "evidence:announce",
      };
    });

    // The fault is not a classification: it escapes the door untouched —
    // but only after the hook stage's write-ahead start is durable.
    expect(() =>
      engine.run(runRequest(world, "main", [beta], { ...declaration, hookEffects: effects })),
    ).toThrow("the announce webhook crashed mid-flight");
    expect(invocations).toBe(1);
    const attemptId = capturing.attemptIds[0];
    const planId = capturing.planIds[0];
    if (attemptId === undefined || planId === undefined) {
      throw new Error("fixture broken: the ledger captured no attempt write");
    }
    expect(stores.ledger.step(attemptId, "hook:announce")).toBe("started");

    // The resume classifies from the recorded tail — never a re-plan — and
    // the effect runs exactly once more, to the published terminal.
    const outcome = engine.resume(
      crashedHandle(planId, attemptId),
      runRequest(world, "main", [beta], { ...declaration, hookEffects: effects }),
    );
    expect(outcome.kind).toBe("published");
    if (outcome.kind !== "published") {
      throw new Error("expected a published outcome");
    }
    expect(outcome.tag).toBe(GOLDEN.ladder[0]);
    expect(invocations).toBe(2);
    expect(recordedTos(stores.ledger.tail(attemptId), "hook:announce")).toStrictEqual([
      "started",
      "completed",
    ]);
  });

  it("memory-07 · W1 × I7 · E-05's stale verdict renders at the surface through the port-seam wrapper", () => {
    const stores = freshStores();
    const shifting = new ShiftingLedger(stores.ledger);
    const engine = assembleMemoryStores(
      {
        register: stores.register,
        ledger: shifting,
        claims: stores.claims,
        channels: stores.channels,
      },
      { maxRetries: 2 },
    );
    const stopped = engine.run(runRequest(liveWorld(), "main", [beta], attestDeclaration()));
    expect(stopped.kind).toBe("blocked");
    const again = engine.run(runRequest(liveWorld(), "main", [beta], attestDeclaration()));
    expect(again.kind).toBe("stale");
    if (again.kind !== "stale") {
      throw new Error("expected a stale outcome");
    }
    expect(again.detail).toContain(stopped.planId ?? "plan_sha256:");
    expect(again.detail).toContain(FOREIGN_PLAN);
  });

  it("memory-08 · W1 × I8 · the blocked loop live: blocked, the recorded resolution re-arms, the resumed walk publishes", () => {
    const assembly = freshAssembly();
    const world = liveWorld();
    const stopped = assembly.engine.run(
      runRequest(world, "main", [beta], attestDeclaration(undefined)),
    );
    expect(stopped.kind).toBe("blocked");
    if (stopped.kind !== "blocked" || stopped.handle === null || stopped.planId === null) {
      throw new Error("expected a blocked outcome carrying its plan");
    }
    expect(stopped.cause).toBe("validation:hook:attest:evidence-present");

    const resolved = assembly.engine.resolve(stopped.handle, "hook:attest", {
      kind: "revalidation",
      planFingerprint: stopped.planId,
    });
    expect(resolved.kind).toBe("resolved");
    const mid = assembly.stores.ledger.tail(stopped.handle.attemptId);
    expect(mid.filter((record) => record.kind === "resolution")).toHaveLength(1);

    const outcome = assembly.engine.resume(
      stopped.handle,
      runRequest(world, "main", [beta], attestDeclaration("evidence:attest")),
    );
    expect(outcome.kind).toBe("published");
    if (outcome.kind !== "published" || outcome.handle === null) {
      throw new Error("expected a published outcome");
    }
    expect(outcome.tag).toBe(GOLDEN.ladder[0]);
    expect(
      recordedTos(assembly.stores.ledger.tail(outcome.handle.attemptId), "hook:attest"),
    ).toStrictEqual(["started", "failed", "started", "completed"]);

    // Resumed-equals-uninterrupted (memory-05's pattern, I8's third
    // clause): a walk whose declaration carries the evidence from the
    // start never blocks, and lands the identical published tag.
    const uninterrupted = freshAssembly().engine.run(
      runRequest(liveWorld(), "main", [beta], attestDeclaration("evidence:attest")),
    );
    expect(uninterrupted.kind).toBe("published");
    if (uninterrupted.kind !== "published") {
      throw new Error("expected a published outcome");
    }
    expect(uninterrupted.tag).toBe(outcome.tag);
  });

  it("memory-09 · the store-less channels corner: show channels over A-memory renders the engine's own refusal, never a null", () => {
    const child = runBin(["show", "channels", "--assembly", "memory", "--json"]);
    expect(child.status).toBe(10);
    expect(child.stderr).toBe("");
    const rendered = JSON.parse(child.stdout) as { kind: string; detail?: string };
    expect(rendered.kind).toBe("refused");
    // The engine's own refusal, its text pinned: the corner is the store's
    // absence, not an empty read.
    expect(rendered.detail).toBe(
      "no channel store is wired — the assembly names no channel port, so there is " +
        "nothing to read (phase 11 contract §2.4)",
    );
  });

  it("memory-10 · the zero-random assembly: every memory envelope is byte-identical across runs, with no projection", () => {
    const args = [
      "run",
      "--assembly",
      "memory",
      "--world",
      "-",
      "--actor",
      "automation",
      "--line",
      "main",
      "--json",
    ];
    const doc = docBytes(memoryDoc("main", [beta]));
    const first = runBin(args, { input: doc });
    const second = runBin(args, { input: doc });
    expect(first.status).toBe(0);
    expect(second.stdout).toBe(first.stdout);

    // The boundary side of the posture: two fresh assemblies serialize the
    // same bytes.
    const directFirst = freshAssembly().engine.run(runRequest(liveWorld(), "main", [beta]));
    const directSecond = freshAssembly().engine.run(runRequest(liveWorld(), "main", [beta]));
    expect(JSON.stringify(directFirst)).toBe(JSON.stringify(directSecond));
  });
});
